# This is a basic workflow to help you get started with Actions
class Node:
    def __init__(self, data=None):
        self.data = data  # Значення даних у вузлі
        self.next = None  # Посилання на наступний вузол (за замовчуванням None)

class LinkedList:
    def __init__(self):
        self.head = None  # Початок списку (голова)

    def append(self, data):
        """Додає новий вузол в кінець списку"""
        new_node = Node(data)
        if not self.head:  # Якщо список порожній, новий вузол стає головою
            self.head = new_node
        else:
            last = self.head
            while last.next:  # Знаходимо останній елемент списку
                last = last.next
            last.next = new_node  # Приєднуємо новий вузол

    def display(self):
        """Виводить елементи списку"""
        current = self.head
        while current:
            print(current.data, end=" -> ")
            current = current.next
        print("None")

    def delete(self, data):
        """Видаляє перший вузол зі значенням data"""
        current = self.head
        if current and current.data == data:  # Якщо елемент для видалення - голова списку
            self.head = current.next
            current = None
            return

        prev = None
        while current and current.data != data:
            prev = current
            current = current.next

        if current is None:  # Якщо елемент не знайдений
            print(f"Element {data} not found.")
            return

        prev.next = current.next  # Перепідключаємо попередній вузол до наступного
        current = None  # Видаляємо вузол

    def search(self, data):
        """Шукає елемент у списку"""
        current = self.head
        while current:
            if current.data == data:
                return True
            current = current.next
        return False

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
